// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // CLI/마이그레이션 전용 (direct 연결). Prisma 7의 datasource 설정 타입에는
    // directUrl 필드가 없어져서, CLI가 실제로 참조하는 값은 이 url 하나뿐임.
    url: process.env["DIRECT_URL"],
  },
  // DATABASE_URL(pooled, 6543)은 여기서는 안 쓰고, 나중에 lib/prisma.ts에서
  // @prisma/adapter-pg에 직접 넘겨서 앱 런타임 쿼리용으로 사용할 예정.
});
